Logo component
Angel10050/nailu_project pull request #1
Opened 2019-09-25 03:46 UTC by Angel10050

2019-09-25 13:27 UTC, afmeva requested changes

2019-09-25 13:27 UTC, afmeva commented on src/App.js
> +      <>
No hay necesidad de usar fragments aqui. El componente ya devuelve un solo elemento. Recordar que los Fragments se usan cuando necesitamos devovler un solo elemento pero no queremos que se convierta en un nodo en el DOM

2019-09-25 13:27 UTC, afmeva commented on src/Components/logo/Logo.js
> +            <>
igual aqui. No se necesita el uso de Fragments

2019-09-25 13:27 UTC, afmeva commented on src/Components/logo/Logo.js
> +        scroll.scrollToTop()
Es realmente necesario agregar una dependecia para el manejo del scroll de esta forma?... tambien debe cuidarse el uso de dependencias de manera global.

2019-09-25 13:27 UTC, afmeva commented on src/App.css
> +.imgLogo{
Sugerencia: Usar alguna convencion para el nombramietno de clases.

2019-09-25 13:27 UTC, afmeva commented on package.json
> +    "react-scroll": "^1.7.14"
revisar si es neesario agregar esta dependecia.

2019-10-08 03:23 UTC, Angel10050 commented
@afmeva en el commit anterior el scroll funciona, me queda la duda si eso lo que sugieres o es hacer la función Higher-Order Component para usar ese scroll por ejemplo tambien para los botones. 
quedo atento a las observaciones.

2019-10-08 12:53 UTC, afmeva commented
@Angel10050 Si, esto esta mejor en cuanto al scroll. El Logo podria ser un componente funcional, por lodemas esta bien.

2019-10-08 12:54 UTC, afmeva commented on src/Components/logo/Logo.js
> +class Logo extends Component {
Podria ser funcional. No es obligatorio.

2019-10-08 12:54 UTC, afmeva approved these changes

2019-10-08 15:48 UTC, Angel10050 commented
*7d32115* en este ultimo commit tome la sugerencia de @afmeva , sobre la innecesidad de que Logo fuera un componente de clase, por lo tanto lo cambie a uno de funcion. PD: me disculpan el *tu* tan literal del commit.

2019-10-11 19:49 UTC, minotad66 approved these changes

2019-10-22 23:34 UTC, merged