Milvia
Angel10050/nailu_project pull request #11
Opened 2019-10-28 18:29 UTC by 1000VIA

Cambios sugerido por @Angel10050

2019-10-28 18:30 UTC, Angel10050 approved these changes

2019-10-28 19:26 UTC, minotad66 reviewed
milvia, revisa los enlaces a las redes sociales, cuando esta en una resolución grande (width > 768px) no esta alineado a la otra información, sino que se ve por debajo

2019-10-28 20:56 UTC, minotad66 commented
ya revise bien y el problema fue mio, me falto la parte de font awesome. considero que se ve genial y cumple con ser responsive

2019-10-28 20:57 UTC, minotad66 approved these changes

2019-10-29 02:56 UTC, afmeva requested changes

2019-10-29 02:56 UTC, afmeva commented on src/Components/Footer/Footer.js
> +                <span className="fa fa-whatsapp" aria-hidden="true"></span>
es buena practica tener los aria attributes. En este caso me parece mejor removerlos mientras no tengamos claro su utilidad y funcionamiento.

2019-10-29 02:56 UTC, afmeva commented on src/Components/Footer/Footer.js
> +      <div className="container">
quizas este div no es necesario

2019-10-29 02:56 UTC, afmeva commented on src/Components/Footer/Style.css
> +.container {
muchas de las reglas de css usadas pudieron ser usadas con los utils de bootstrap. No hay que ambiar este archivo por el mmomento, pero tener en cuenta para los componentes que se van a desarrollar.

2019-10-29 02:56 UTC, afmeva commented on src/Components/Footer/Style.css
> +.container {
no es buena idea agregar estilos a las clases de bootstraap. Es mejor crear clases neuvas para esto. Modificar las clases existentes de bootstrap podrian afectar otros componentes que esten usando las mismas clases. Por otro lado tampoco es buena idea dar estilos directametne sobre la etiqueta como por ejemplo ```h2``` o ```a```

2019-10-29 03:25 UTC, 1000VIA commented on src/Components/Footer/Footer.js
> +      <div className="container">
Solucionado

2019-10-29 03:34 UTC, 1000VIA commented on src/Components/Footer/Footer.js
> +                <span className="fa fa-whatsapp" aria-hidden="true"></span>
Corregido!

2019-10-29 12:12 UTC, afmeva approved these changes

2019-10-29 12:12 UTC, afmeva commented on src/Components/Footer/Style.css
> +a:hover {
creo que esto deberia ser ```links:hover```

2019-10-29 12:29 UTC, merged