Develop form
Angel10050/nailu_project pull request #12
Opened 2019-10-29 01:02 UTC by Angel10050

todos los campos tienen verificaciones para que no esten vacios, el email ademas para que culpla con su estructura y recibe el boton de los ya creados antes como otros componentes,
los estilos son sencillos ya que aun no se define un estilo para todo es proyecto. dejo a recomendacion que aparesca un texto debajo del campo invalido con su respectiva obsevacion, ya que los mensajes ya estas echos pero aun no son visibles

2019-10-29 01:21 UTC, 1000VIA commented on src/Components/form/form.css
> +}
El signo de % en este caso  no es necesario ya que se está aplicando cero a una propiedad.

2019-10-29 01:26 UTC, 1000VIA commented on src/Components/form/Form.js
> +            </form>
Yo le pondría los mensajes de los placeholder en español

2019-10-29 01:26 UTC, 1000VIA commented on src/Components/form/Form.js
> +        : ''
Teniendo en cuenta que es una página para Colombia sería buena cambiar los mensajes de las validaciones y ponerlos en español.

2019-10-29 02:39 UTC, Angel10050 commented on src/Components/form/Form.js
> +            </form>
Si hago eso, tendia que ponerlo todo en español tambien, considero mas global el ingles y mas escalable.

2019-10-29 02:40 UTC, Angel10050 commented on src/Components/form/Form.js
> +        : ''
Reitero, opino que en ingles es mejor.

2019-10-29 02:48 UTC, Addin commented on src/Components/form/Form.js
> +            </form>
Hola Ángel, tienes que tomar en cuenta la accesibilidad y las buenas prácticas, es importante tener en cuenta el público objetivo de este proyecto. Reúnanse y definan si van a dejar los mensajes de error y los placeholder en inglés o los pasan a español.

2019-10-29 02:49 UTC, afmeva requested changes

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/form.css
> +*{
Esta regla sobre todos los componentes no es buen idea. Esta afectando cosas incluso por fuera de este componente. Aqui solo deberian a ver estilos que afecten este componente.

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/Form.js
> +            <input type='text' id='name' name='userName' onChange={this.handleOnChange} placeholder='Enter Your FullName' className='input'/>
mejor usar inputs controlados, es decir, que este conectados al state

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/Form.js
> +       event.preventDefault()
esto deberia estar manajenado el objecto que se va a enviar al servidor. Por otro lado deberia exponer un callback para ser ejecutado en el onSubmit

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/Form.js
> +        isInvalid : true,
pareciera que esta varible solo controla la validez del email, alguna razon para eso?

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/Form.js
> +    fieldvalidation = ( id, value ) => {
esto podria simplificarse y refactorizarse. Otra opcion seria remover todas las validaciones, desde la planeacion habiamos quedado en no tener validaciones en el front. 

En todo caso si se siente que se puede tener validaciones sin afectar tiempos de entrega, perfecto dejarlas.

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/Form.js
> +import React,{ Component } from "react"
REvisar la indentacion de este archivo.

2019-10-29 02:49 UTC, afmeva commented on src/Components/form/form.css
> +*{
muchas de las reglas usadas pudieron haberse ehcho usando las utilidades de bootstrap. A este punto no hay que eliminar los CSS, pero si tener presetne esto para futuros componentes.

2019-10-29 02:51 UTC, afmeva commented
Parece que este PR esta eliminando el cmponente del logo. Revisar bien para que no vayan a eliminarlo

2019-10-29 16:43 UTC, Angel10050 commented on src/Components/form/Form.js
> +    fieldvalidation = ( id, value ) => {
en la tarea de trello, dice que este componente debe tener validaciones.

2019-10-29 16:43 UTC, Angel10050 commented on src/Components/form/Form.js
> +    fieldvalidation = ( id, value ) => {
En la tarea de trello decia que este formulario debia tener validaciones, siendo una de la tareas de front-end, lo hice sujeto a eso

2019-10-29 16:44 UTC, Angel10050 commented on src/Components/form/Form.js
> +        isInvalid : true,
no, no solo controla la validez del email, controla la validez de todos los campos

2019-10-30 13:22 UTC, afmeva requested changes

2019-10-30 13:22 UTC, afmeva commented on src/Components/form/form.css
> +input:focus {
No es recomendable cambiar estilos sobre la etiqueta. Es mejor hacerlo a traves de un selector de CSS

2019-10-30 17:35 UTC, closed without merging