Complete form applying recommendations, in addition to Spanish as an …
Angel10050/nailu_project pull request #17
Opened 2019-10-30 17:58 UTC by Angel10050

por errores en mi repo local y mis ramas cerre y re-abri el pullrequest, esta vez el formulario tiene el español como idioma acordado y se aplicaron las sugerencias echas por los revisadores del pull anterior

2019-10-30 18:15 UTC, 1000VIA approved these changes
Me gusta, quedó mucho más limpio el código

2019-10-30 18:36 UTC, afmeva commented on src/Components/form/Form.js
> +       event.preventDefault()
Sigue pendiene el tema de recibir un callback ```onSubmit``` por ejemplo para hacer el request. Este callback debe recibir como como parametro la info del formulario (state)

2019-10-30 18:37 UTC, afmeva requested changes
En general quedó mucho mas limpio. Porfa agregar el callback para el submit.

2019-10-30 18:42 UTC, jolki3e4r approved these changes

2019-10-31 18:55 UTC, Angel10050 commented
intente hacer lo del callback que dices @afmeva no se si te referias ha converti la info que queda en el estado lista para enviar(info parseada) ps la etiqueta form ya recive la funcion onsubmit y el boton es de tipo submit too

2019-10-31 19:14 UTC, afmeva approved these changes

2019-10-31 19:14 UTC, afmeva commented on src/Components/form/Form.js
> +       const InfoToJson = JSON.stringify(this.state)
esto es inncesario. EStas trasformando el state a string y luego otra vez a un objeto. Vamos a aprobarlo y luego deifnimos bien como queremos definir el manejo de la info necesaria para hacer el request

2019-10-31 22:35 UTC, merged