Develop admin page
Angel10050/nailu_project pull request #19
Opened 2019-10-31 18:45 UTC by Angel10050

esta es la pagina del administrador esta conformada por imagenes de ejemplo sobre que es el contenido que va modificar,(las imagenes que estan en este momento solo son de prueba y no estan responsivas) ademas creo que es importante decir que empece diria confundido pero la realizacion fue fluyendo, primero todo estaba en un solo componente y despues vi que podia reutilizar varias cosas por lo que se separo en diferente componentes, asi que son varias carpetas, el formulario tiene un ONSUBMIT que se conecta a una funcion esta funcion previene el recargado de la pagina y ademas convierte la informacion de este a json. osea esta parseada esa informacion. quedo antento

2019-11-01 22:37 UTC, IvanVilla1585 commented
please, resolve conflicts.

2019-11-02 17:02 UTC, IvanVilla1585 commented
pease, resolve conflicts.

2019-11-02 20:45 UTC, afmeva requested changes

2019-11-02 20:45 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        const infoToJson = JSON.stringify(this.state)
esto es innecesario, se esta transfomrando el state a string y luego otra vez a un objeto. TAmpoco se esta usando. Remover antes de mergear

2019-11-02 20:45 UTC, afmeva commented on src/Components/form/Form.js
> +import React,{ Component } from "react"
ESte archivo no pertenece a esta tarea

2019-11-02 20:45 UTC, afmeva commented on src/Components/form/form.css
> +.formContainer {
Este archivo no pertenece a esta tarea

2019-11-02 22:23 UTC, Angel10050 commented on src/Components/form/form.css
> +.formContainer {
Si, creo que tube una mala practica añ editar otros archivos fuera de mi tarea, no pasara otra vez.

2019-11-02 22:24 UTC, Angel10050 commented
ya elimine los metodos innecesarios.

2019-11-04 02:27 UTC, afmeva approved these changes

2019-11-04 02:27 UTC, afmeva commented on src/App.js
> +            <Route exact path="/admin/content">
es necesario la proiedad `exact` aca?

2019-11-04 02:48 UTC, Angel10050 commented on src/App.js
> +            <Route exact path="/admin/content">
Si,
deshabilita la coincidencia parcial para una ruta y se asegura de que solo devuelva la ruta si la ruta es una coincidencia EXACTA con la url actual.

Que opinas y sigieres tu?

2019-11-04 02:50 UTC, Angel10050 commented on src/App.js
> +            <Route exact path="/admin/content">
O sera que solo no necesita la ruta** /user** y **user/admin** no

2019-11-04 02:51 UTC, Angel10050 commented on src/App.js
> +            <Route exact path="/admin/content">
O sera que solo no necesita la ruta 
**/user** y user/admin 
no

2019-11-04 02:51 UTC, Angel10050 commented on src/App.js
> +            <Route exact path="/admin/content">
O sera que solo no necesita la ruta **/user** y **user/admin** no.

2019-11-04 03:24 UTC, 1000VIA approved these changes

2019-11-04 03:30 UTC, merged