Box component
Angel10050/nailu_project pull request #25
Opened 2019-11-01 20:30 UTC by 1000VIA

2019-11-02 15:27 UTC, Angel10050 requested changes

2019-11-02 15:27 UTC, Angel10050 commented on src/Components/BoxComponent/StyleBoxComponent.css
> +}
seria mejor poner la media a partir de 761px, osea asi tal cual pero con la media de 761px.

2019-11-02 15:27 UTC, Angel10050 commented on src/Components/BoxComponent/StyleBoxComponent.css
> +}
Aun tienes un problemas de scroll orizontal cuando se activa la media query, te recomiendo decirle a la clase  ".Text" que tenga una margen de 0px ya que es la margen quien te procuce ese scroll. :)

2019-11-02 20:36 UTC, Angel10050 approved these changes

2019-11-02 20:43 UTC, afmeva requested changes

2019-11-02 20:43 UTC, afmeva commented on src/Components/navComponent/NavComponent.js
> +import React from 'react'
este archivo no pertenece a esta terea. Asi sea un cambio de comillas y punto y comas. Esto no deberia estar aqui. Esto se puede evitar con un .editorconfig file

2019-11-02 20:43 UTC, afmeva commented on src/Components/navComponent/NavComponentStyle.css
> +.responsiveNavbar {
no pertenece a esta tarea. No hay que removerlo pero tener en cuenta para el futuro

2019-11-02 20:43 UTC, afmeva commented on src/Components/adminPage/Login/loginUser.js
> +      <div className="container login containerLogin">
no pertence a esta tarea. No hay que removerlo pero tenerlo en cuenta para el futuro

2019-11-02 20:43 UTC, afmeva commented on src/Components/BoxComponent/StyleBoxComponent.css
> +.Text {
algunasc clases estan comenzando con mayusculas y otras no. Mantener consistencia

2019-11-02 20:43 UTC, afmeva commented on src/Components/BoxComponent/StyleBoxComponent.css
> +  margin: 20px 0 20px 0;
esto es lo mismo que ```margin: 20px 0```

2019-11-02 22:13 UTC, 1000VIA commented on src/Components/BoxComponent/StyleBoxComponent.css
> +.Text {
Solucionado

2019-11-02 22:13 UTC, 1000VIA commented on src/Components/BoxComponent/StyleBoxComponent.css
> +  margin: 20px 0 20px 0;
Cambiado

2019-11-02 22:14 UTC, 1000VIA commented on src/Components/adminPage/Login/loginUser.js
> +      <div className="container login containerLogin">
Gracias, no había pensado en eso.

2019-11-02 22:15 UTC, 1000VIA commented on src/Components/navComponent/NavComponentStyle.css
> +.responsiveNavbar {
Lo tendré encuenta, gracias

2019-11-02 22:16 UTC, 1000VIA commented on src/Components/navComponent/NavComponent.js
> +import React from 'react'
Si, estaba cometiendo ese tipo de errores, los tendré en cuenta para la próxima vez

2019-11-03 01:15 UTC, afmeva approved these changes

2019-11-03 01:30 UTC, merged