creacion del componente galley tipo grid
Angel10050/nailu_project pull request #28
Opened 2019-11-03 20:26 UTC by jolki3e4r

2019-11-03 21:24 UTC, 1000VIA commented on src/Components/gallery/StyleGallery.css
> +    grid-gap: 5px;
Identar el código para que no se vea tan desorganizado.

2019-11-03 21:24 UTC, 1000VIA commented on src/Components/gallery/StyleGallery.css
> +                       "1fr 1fr 1fr" 250px;
Lo mismo: Identar el código para que no se vea tan desorganizado.

2019-11-03 21:29 UTC, Angel10050 requested changes

2019-11-03 21:29 UTC, Angel10050 commented on src/Components/gallery/StyleGallery.css
> +}
Este estilo en **.galleryContent** donde with es 100vw no funciona para la forma en que el with de la pagina esta ajustado, te recomiendo ver cual es el with del componente footer y usarlo para **.galleryContainer** ya que como lo tienes en este momento genera un scroll horizontal.

2019-11-03 21:29 UTC, Angel10050 commented on src/Components/gallery/StyleGallery.css
> +}
ademas este componente esta pegado al footer, separalo un poquito.

2019-11-03 22:59 UTC, jolki3e4r commented on src/Components/gallery/StyleGallery.css
> +                       "1fr 1fr 1fr" 250px;
identacion organizada

2019-11-03 23:03 UTC, jolki3e4r commented on src/Components/gallery/StyleGallery.css
> +}
ya le agregue un margen y esty trabajando en el scroll

2019-11-04 00:56 UTC, 1000VIA commented on src/Components/gallery/StyleGallery.css
> +}
La idea es que le pongas un **margin-bottom:  20px.** a la **.galleryContainer**

2019-11-04 00:57 UTC, 1000VIA approved these changes

2019-11-04 02:36 UTC, afmeva requested changes

2019-11-04 02:36 UTC, afmeva commented on public/index.html
> +    <link rel=”shortcut icon” type=”image/png” href=”/favicon.png”/>
si no tienen favicon esta linea podria removerse

2019-11-04 02:36 UTC, afmeva commented on src/App.css
> +    /* background: #343a40; */
remover si no se necesita

2019-11-04 02:36 UTC, afmeva commented on src/Components/gallery/StyleGallery.css
> +
Estoy podria plantearse un poco diferente. De momento esta bien, en el momento de volver esto mas dinamico se puede revisar

2019-11-05 15:25 UTC, afmeva approved these changes

2019-11-05 19:05 UTC, minotad66 approved these changes

2019-11-05 19:07 UTC, Angel10050 approved these changes

2019-11-05 19:08 UTC, merged