Enpoint back
Angel10050/nailu_project pull request #29
Opened 2019-11-03 21:01 UTC by minotad66

WIP Aquí subo los endpoint de prueba con los datos quemados pero con la parte de la de la autenticacion y validacion de datos,

2019-11-03 22:38 UTC, afmeva requested changes

2019-11-03 22:38 UTC, afmeva commented on server/src/utils/index.js
> +  props.forEach(key => {
se puede hacer con un `some` o un `every`

2019-11-03 22:38 UTC, afmeva commented on server/src/routes/contact.js
> +    const valid = validateData(
seria bueno tambien validar los tipos de datos aca.

2019-11-03 23:05 UTC, 1000VIA approved these changes

2019-11-04 02:39 UTC, afmeva requested changes

2019-11-04 02:39 UTC, afmeva commented on server/src/utils/index.js
> +  console.log("esto es una prueba", regExpPassword.test(value));
remover esto

2019-11-04 02:39 UTC, afmeva commented on package.json
> +    "dev": "nodemon"
este script es para que?

2019-11-04 02:49 UTC, minotad66 commented on package.json
> +    "dev": "nodemon"
sirve para hacer pruebas de desarrollo, recarga el servidor cuando se realiza un cambio, es para probar , luego lo elimino

2019-11-04 03:01 UTC, minotad66 reviewed
elimine a nodemon ya que solo re requiere para recargar el servidor en el local y elimine el console.log

2019-11-04 03:01 UTC, minotad66 commented on server/src/utils/index.js
> +  console.log("esto es una prueba", regExpPassword.test(value));
creo que se refiere al console.log, el cual ya fue borrado

2019-11-04 03:19 UTC, afmeva approved these changes

2019-11-04 03:22 UTC, merged