Develop link to routes
Angel10050/nailu_project pull request #44
Opened 2019-11-06 06:09 UTC by Angel10050

chicxs en esta rama lo que se hizo fue que los botones de las cartas de eventos lleven el usuario al formulario para pedir ser contactado, quedo atento a sus revisiones y respuestas.

2019-11-06 14:24 UTC, 1000VIA approved these changes

2019-11-06 14:25 UTC, jolki3e4r approved these changes

2019-11-06 14:51 UTC, afmeva requested changes

2019-11-06 14:51 UTC, afmeva commented on src/Components/BoxComponent/BoxComponent.js
> +                <Link to='/user/contactme' className='link'><ButtonGeneral type="button" nameBtn="Información" /></Link>
quizas lo mejor sea hacer un componente para el link que reciba como propiedad la url. De esta manera se puede reutilizar en la app manteniendo los estilos.

2019-11-06 18:52 UTC, Angel10050 commented
se crea el componente para el link y se usan props

2019-11-07 12:58 UTC, afmeva commented on src/Components/BoxComponent/BoxComponent.js
> +                <Route to='/user/contactme' className='link' button={<ButtonGeneral type="button" nameBtn="Información" />}/>
es necesario enviar el cmopneten de boton? podria estar directametne en el que se creó.

2019-11-07 20:47 UTC, afmeva commented on src/Components/routeComponent/Route.js
> +             <ButtonGeneral type="button" nameBtn="Información" />
pasar el nombre tambien como propiedad

2019-11-08 13:18 UTC, afmeva approved these changes

2019-11-08 15:09 UTC, merged