change way of handleErrors
Angel10050/nailu_project pull request #57
Opened 2019-11-08 20:54 UTC by Angel10050

este pull es para reparar la forma en que se le daba feedback al usuario en todos lo formularios de la app, ya habia trabajado en una rama para eso y habia sido aprovada pero las cosas no estaban funcionando muy bien, pido disculpas por no revisar bien antes del crear el pull.

en este pull aun no se hace nada con el segundo then de los fetch ni con los catch por lo tanto de encuentran con un console log, eso no va a quedar ahi, estoy bucando que hacer con eso aun (si tienen sigerencias son bien recibidas)
 
como lo estaba entendiendo antes no tenia sentido, pero con este enfoque es mas claro para mi.

2019-11-08 21:40 UTC, jolki3e4r approved these changes

2019-11-08 21:48 UTC, afmeva requested changes

2019-11-08 21:48 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        .then(console.log())
puede usarse un toast o snackbar de boostrap para mostrar los errores. O su forma mas simple un `alert`

2019-11-08 21:48 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        .then(response => response.json() && response.ok ? this.setState({error : false}) : this.setState({error : true}) )
esto seria mas claro agregando una funcion en el cuerpo entero. Tambien se puede cambiar un poco el flujo de esto para encadenar varios `then`

2019-11-08 21:48 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        .catch(console.log())
pienso que igual en el catch deberia manejarse el error con el state

2019-11-08 21:48 UTC, afmeva commented on src/Components/form/Form.js
> +      .then(response => response.json() && response.ok ? this.setState({error : false}) : this.setState({error : true}) )
aplica los mismo comentario santeriores.

2019-11-08 21:51 UTC, Angel10050 commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        .then(console.log())
porque no la la cajita de respuesta que ya esta creada?

2019-11-09 20:57 UTC, Angel10050 commented
En este pull request solo se manejaran los errores y el feedback del usuario tanto del admin como del customer, se deja por fuera de este pull request el feedback  y manejo de errores de la pagina del administrador de contenidos, ademas se terminara de configurar el token en otra rama.

2019-11-09 23:28 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        .then(console.log())
tambien esta bien.

2019-11-10 02:23 UTC, afmeva approved these changes

2019-11-10 07:57 UTC, merged