nav component
Angel10050/nailu_project pull request #7
Opened 2019-10-25 16:48 UTC by minotad66

hola, este es el navcomponet no esta terminado y me gustaría sabe que opiniones tienen, esta responsive, para esto se utilizo react-bootstrap, que le puedo agregar, siento que el color es perfecto para el logo, ensaye con blanco y se ve horrible. agregue una función que me redirige a google.com, solo para comprobar el funcionamiento de los botones, ya que no este el contenido interno al cual va a ir ligado

2019-10-25 19:23 UTC, 1000VIA commented on src/Components/navButtonComponent/navButtonStyle.css
> +}
Tengo entendido que si estamos usando Bootstrap no se necesita de mediaquery ya que bootstra tiene sus propias clases para que las cosas sean responsive.
Si me estoy equivocando en algo por favor me lo hacen saber.

2019-10-25 19:35 UTC, afmeva requested changes

2019-10-25 19:35 UTC, afmeva commented on src/Components/navButtonComponent/navButtonStyle.css
> +@media (max-width: 767.98px) {
es mejor tener medidas exactas. Quizas lo que necesita aca es el `min-width` en lugar del `max-width`

2019-10-25 19:35 UTC, afmeva commented on src/Components/navButtonComponent/navButtonStyle.css
> +}
ESta bien usar media queries. Algunas veces es necesario, lo importante estar seguros que bootstrap no les ofrezaca ya una clase con la utlidad que necesitan.

2019-10-25 19:35 UTC, afmeva commented on src/Components/navComponent/nav_component.js
> +  handleClickButtonNav = ({ target: { name } }) => {
este switch no deberia ser necesario. Solo dbe enviarse un callback a cada uno de los botones dentro del menu, incluso si solo van a ser enrutamientos la misma etquita anchor se haria cargo de esto sin necesidad de funciones adicionales.

2019-10-25 19:35 UTC, afmeva commented on src/Components/navComponent/nav_component.js
> +  functionProbe = name => {
en el codigo final tener cuidado con los nombres de las funciones

2019-10-25 19:35 UTC, afmeva commented on src/Components/navComponent/nav_component.js
> +import { Nav, Navbar } from "react-bootstrap";
recuerden que para nuevas dependecias el equipo debe estar de acuerdo

2019-10-25 19:35 UTC, afmeva commented on src/Components/navComponent/navComponentSyle.css
> +@media (max-width: 767.98px) {
de neuvo, media quries exactos.

2019-10-25 19:35 UTC, afmeva commented on src/Components/navComponent/navComponentSyle.css
> +.component--flex {
recordar la consitencia en el nombramiento de clases. Mantener una sola convencion

2019-10-25 19:36 UTC, afmeva commented
MAntener la convencion tambien en los nombres de los archivos, algunos estan en camel case y otros con guiones

2019-10-25 19:38 UTC, afmeva commented
el navButton esta por fuera del alcance de esta historia. En vista de que ya hay algo adelantado ponerse en contacto con la persona que tenga a cargo esta tarea (navButton) y alinarse para evitar trabajo repetido

2019-10-25 22:18 UTC, minotad66 commented on src/Components/navButtonComponent/navButtonStyle.css
> +@media (max-width: 767.98px) {
la verdad me di cuenta que lo necesitaba, lo que pretendía hacer lo puedo hacer desde, clase como tal, sin necesidad del tamaño de la pantalla

2019-10-25 22:20 UTC, minotad66 commented on src/Components/navComponent/nav_component.js
> +  handleClickButtonNav = ({ target: { name } }) => {
es que me confundí con la palabra callback, lo tenia asociado siempre a una función, pero ya logre solucionarlo

2019-10-25 22:22 UTC, minotad66 commented on src/Components/navComponent/nav_component.js
> +import { Nav, Navbar } from "react-bootstrap";
yo les pregunte si estaban de acuerdo, es que con el bootstrap normal no funcionaba perfectamente el nav responsive y en este si funciono y para no perder mucho tiempo investigando el porque no funcionaba o haciéndolo desde cero, utilice esta dependencia

2019-10-29 02:48 UTC, 1000VIA commented on src/Components/Button/Button.js
> +};
Recuerda que los nombres de las clases en React es: className

2019-10-29 03:19 UTC, minotad66 commented on src/Components/navComponent/nav_component.js
> +  functionProbe = name => {
esa funcion era de prueba pero la elimine porque me di cuenta que no la necesitaba

2019-10-29 03:20 UTC, minotad66 commented on src/Components/navComponent/navComponentSyle.css
> +.component--flex {
y lo corregi, en el grupo se llego a la decision de usar el camelCase

2019-10-29 18:51 UTC, afmeva approved these changes

2019-10-29 19:08 UTC, 1000VIA approved these changes

2019-10-29 19:27 UTC, merged

2019-10-29 19:31 UTC, Addin commented on src/App.js
> +        <ButtonGeneral type='button' nameBtn='Mas informacion' callback={this.handlerClick} />
Mucho cuidado con los errores ortográficos, "**Inscríbete**" "**Más información**".