Fix stlyes
Angel10050/nailu_project pull request #71
Opened 2019-11-12 21:27 UTC by Angel10050

en este pull request se arreglan los estilos de la app teniendo en cuenta la sugerencia de los metores, se quitan hovers de los fomularios, se encapsulan mensajes de error dentro de los formularios, se arreglan los hovesr pegados en dispositivos mobil y arrelga el menu amburguesa para que tenga mas relevancia y se vea

2019-11-13 04:05 UTC, afmeva requested changes

2019-11-13 04:05 UTC, afmeva commented on src/Components/AdminPage/AdminForm/adminFormStyle.css
> -.adminForm:hover {
la idea es que los hover funcionen en donde peuden funcionar. No quitarlos para todo los dipositivos. Remover solo si se eta seguro que esto es lo que se quiere en este caso.

2019-11-13 04:05 UTC, afmeva commented on src/Components/BoxComponent/StyleBoxComponent.css
> +  .caseBox:hover, .caseBoxReverse:hover {
porque no usar los mismos seletores de la linea 22?

2019-11-13 22:40 UTC, Angel10050 commented on src/Components/BoxComponent/StyleBoxComponent.css
> +  .caseBox:hover, .caseBoxReverse:hover {
despues de hablar con el quipo se decidio que no queriamos los hover en dispositivos de pantallas pequeñas

2019-11-14 14:16 UTC, afmeva commented on src/Components/BoxComponent/StyleBoxComponent.css
> +  .caseBox:hover, .caseBoxReverse:hover {
ok, eso esta bien. Pero es buena idea no duplicar selectores.

2019-11-15 01:39 UTC, 1000VIA approved these changes

2019-11-15 01:49 UTC, minotad66 approved these changes

2019-11-15 01:57 UTC, merged