borrar token vencido
Angel10050/nailu_project pull request #79
Opened 2019-11-14 04:46 UTC by minotad66

se agrega el código para evitar que se entre a la pagina de contenido, cuando el token haya vencido, cuando el token se vence, se redirecciona al login y se borra del local storage el token viejo

2019-11-14 10:19 UTC, 1000VIA approved these changes

2019-11-14 14:22 UTC, afmeva requested changes

2019-11-14 14:22 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +    fetch('api/autorizacion', {method: 'POST',
quizas esto sea mejor hacerse como parte del flujo cuando `api/training` es llamado, en lugar de hacer un llamado adicional. Por otro lado esto no garantiza que cuadno eltoken es invalido el usuario sea redireccionado.

2019-11-14 18:20 UTC, afmeva requested changes

2019-11-14 18:20 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +        console.log(response);
remover console

2019-11-14 18:20 UTC, afmeva commented on src/Components/AdminPage/AdminForm/AdminForm.js
> +          localStorage.removeItem('token'); this.props.history.push('/admin')
poner salto de linea despeues de remover el token

2019-11-14 18:20 UTC, afmeva commented on src/Components/AdminPage/UserList/UserList.js
> +        if(data.ok !== false){
mejor ```if(data.ok)```

2019-11-14 18:20 UTC, afmeva commented on src/Components/AdminPage/UserList/UserList.js
> +      .then(data =>{
Esto podria incluir logica tambien para redireccionar en caso de que el token sea invalido. Por ahora podemos dejarlo como esta.

2019-11-15 02:04 UTC, Angel10050 approved these changes

2019-11-15 02:04 UTC, merged