Jhonatan
Angel10050/nailu_project pull request #8
Opened 2019-10-26 04:00 UTC by jolki3e4r

creacion del box component y pendiente de la visualizacion de la imagen de lados opuestos

2019-10-26 04:12 UTC, 1000VIA commented on src/App.js
> +  // }
Recuerda quitar los comentarios cuando vallas a hacer push para que el código se vea más limpio.

2019-10-26 04:12 UTC, 1000VIA commented on src/index.css
>      sans-serif;
Sería chevere que para el tipo de letra nos pusiéramos de acudo todo el equipo para que podamos manejar un standar.

2019-10-27 00:30 UTC, afmeva requested changes

2019-10-27 00:30 UTC, afmeva commented on package.json
> +    "bootstrap": "^4.3.1",
alinearse con el equipo para saber de que manera van a usar bootstrap. Actualmente estan agregandolo a traves del index de la app.

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/BoxComponent.css
> +.Btncss{
definir una convencion apra el nombraimiento de clases  y manternse con ella. Debería todoas las clases iniciar con minusculas?

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/boxComponentImg.js
> +                                    <img className="img-fluid  mb-3 mb-md-0 imgCss" src={dato.imagenUrl} alt="imagen del evento" />
organizar la indentacion

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/boxComponentImg.js
> +                    this.props.datos.map((dato, index) => {
pareciera que la propoiedad para configurar la orientacion de la imagen no esta. Se va aimplementar eso como un componetne aparte?

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/BoxComponent.css
> +.imgCss{
el sufijo 'css' quias no sea necesaario. Por definicion los selectores hacen alucion a CSS

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/BoxComponent.css
> +    height: 20em;
usar tamaÑos en 'em' tiene riesgos asociadeos. Los espacios no deberian estar asociados al tamaÑo de la fuente

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/BoxComponent.css
> +    justify-items: center;
linea duplicada

2019-10-27 00:30 UTC, afmeva commented on src/components/boxComponentImg/BoxComponent.css
> +
muchas de las reglas usadas para CSS pudieron haberse evitado usando los utils de Bootstrap. Quizas ya noes momento para remover todo esto pero tenerlo en ceunta para los futuros componentes.

2019-10-31 21:28 UTC, closed without merging